name: Sync to Arsana Bot
on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to Arsana Bot repository
        env:
          TARGET_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          echo "Starting sync to Arsana Bot repository..."
          git remote add bot https://${{ secrets.SYNC_TOKEN }}@github.com/your-username/arsana-bot.git
          git push bot main:main --force
