name: Sync to ArsanaLabsBot Fork
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-to-bot:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArsanaLabs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Push to ArsanaLabsBot
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          echo "Syncing changes to ArsanaLabsBot..."
          # Add the bot repository as a remote
          git remote add bot https://${TOKEN}@github.com/ArsanaLabsBot/arsana-easyer.git
          
          # Fetch all branches from bot repository
          git fetch bot
          
          # Push changes to the bot repository
          git push bot main:main --force
          
          echo "Sync completed successfully"
