name: Sync Repositories
on:
  pull_request:
    types: [closed]
    branches:
      - main  # or your default branch name

jobs:
  sync-repos:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to target repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add target repository as a remote
          git remote add target https://${{ secrets.GITHUB_TOKEN }}@github.com/ArsanaLabsBot/arsana-easyer.git
          
          # Push to target repository
          git push target main:main --force
    env:
      GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
